#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
version: '3.3'
services: 
  webui:
    image: ${WEBUI_IMAGE}    
    networks:
      - openamtnetwork
    build:
      context: ./sample-web-ui
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      RPS_SERVER: https://${MPS_COMMON_NAME}:8081
      MPS_SERVER: https://${MPS_COMMON_NAME}:3000
      RPSXAPIKEY: ${RPS_XAPIKEY}
      MPSXAPIKEY: ${MPS_XAPIKEY}
    volumes:
      - ./sample-web-ui/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3001:80
  rps:
    image: ${RPS_IMAGE}
    networks:
      - openamtnetwork
    build:
      context: ./rps
      dockerfile: ./Dockerfile
    ports: 
      - "${RPS_WEBSOCKETPORT}:${RPS_WEBSOCKETPORT}"
      - "${RPS_WEB_PORT}:${RPS_WEB_PORT}"
    depends_on: 
      - mps
    environment: 
      RPS_USE_VAULT: ${RPS_USE_VAULT}
      RPS_NODE_ENV: ${RPS_NODE_ENV}
      RPS_HTTPS: ${RPS_HTTPS}
      RPS_USE_DB_PROFILES: ${RPS_USE_DB_PROFILES}
      RPS_DB_HOST: ${RPS_DB_HOST}
      RPS_DB_NAME: ${RPS_DB_NAME}
      RPS_DB_PORT: ${RPS_DB_PORT}
      RPS_DB_USER: ${RPS_DB_USER}
      RPS_DB_PASSWORD: ${RPS_DB_PASSWORD}
      RPS_WEBSOCKETTLS: ${RPS_WEBSOCKETTLS}
      RPS_WEB_PORT: ${RPS_WEB_PORT}
      RPS_WEBSOCKETPORT: ${RPS_WEBSOCKETPORT}
      RPS_XAPIKEY: ${RPS_XAPIKEY}
      RPS_VAULT_ADDRESS: ${RPS_VAULT_ADDRESS}
      RPS_VAULT_TOKEN: ${RPS_VAULT_TOKEN}
      RPS_SECRETS_PATH: ${RPS_SECRETS_PATH}
      RPS_CREDENTIALS_PATH: ${RPS_CREDENTIALS_PATH}
      RPS_USER: ${RPS_MPS_USER}
      RPS_PASSWORD: ${RPS_MPS_PASSWORD}
      RPS_AMT_USER: ${RPS_AMT_USER}
      RPS_WEB_TLS_CERT: ${RPS_WEB_TLS_CERT}
      RPS_WEB_TLS_CERT_KEY: ${RPS_WEB_TLS_CERT_KEY}
      RPS_ROOT_CA_CERT: ${RPS_ROOT_CA_CERT}
      RPS_LOG_LEVEL: ${RPS_LOG_LEVEL}
      RPS_CORS_ORIGIN: http://${MPS_COMMON_NAME}:3001
      RPS_CORS_HEADERS: ${CORS_HEADERS}
      RPS_CORS_METHODS: ${CORS_METHODS}
      RPS_CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
      RPS_MPS_SERVER: https://${MPS_COMMON_NAME}:${MPS_WEB_PORT}
    volumes:
      - private-volume:/rcs-microservice/private
    command: >
      /bin/bash -c "
        while ! nc -z mps 3000;
        do
          echo waiting for mps;
          sleep 5;
        done;
        echo MPS Running!;
        node ./dist/Index.js;
      "
  mps:
    image: ${MPS_IMAGE}
    networks:
      - openamtnetwork
    build:
      context: ./mps
      dockerfile: ./Dockerfile
    ports: 
      - "${MPS_WEB_PORT}:${MPS_WEB_PORT}"
      - "${MPS_PORT}:${MPS_PORT}"
    environment: 
      MPS_GENERATE_CERTS: ${MPS_GENERATE_CERTS}
      MPS_COMMON_NAME: ${MPS_COMMON_NAME}
      MPS_NODE_ENV: ${MPS_NODE_ENV}
      MPS_USE_ALLOWLIST: ${MPS_USE_ALLOWLIST}
      MPS_PORT: ${MPS_PORT}
      MPS_WEB_PORT: ${MPS_WEB_PORT}
      MPS_USERNAME: ${MPS_USER}
      MPS_PASS: ${MPS_PASSWORD}
      MPS_USE_GLOBAL_CREDENTIALS: ${MPS_USE_GLOBAL_CREDENTIALS}
      MPS_ENABLE_LOGGING: ${MPS_ENABLE_LOGGING}
      MPS_DEBUG: ${MPS_DEBUG}
      MPS_USE_VAULT: ${MPS_USE_VAULT}
      MPS_VAULT_ADDRESS: ${MPS_VAULT_ADDRESS}
      MPS_VAULT_TOKEN: ${MPS_VAULT_TOKEN}
      MPS_SECRETS_PATH: ${MPS_SECRETS_PATH}
      MPS_WEB_ADMIN_USER: ${MPS_WEB_ADMIN_USER}
      MPS_WEB_ADMIN_PASSWORD: ${MPS_WEB_ADMIN_PASSWORD}
      MPS_HTTPS: ${MPS_HTTPS}
      MPS_MPSXAPIKEY: ${MPS_XAPIKEY}
      MPS_LISTEN_ANY: ${MPS_LISTEN_ANY}
      MPS_TLS_OFFLOAD: ${MPS_TLS_OFFLOAD}
      MPS_SESSION_ENCRYPTION_KEY: ${MPS_SESSION_ENCRYPTION_KEY}
      MPS_LOG_LEVEL: ${MPS_LOG_LEVEL}
      MPS_AUTH_ENABLED: ${MPS_AUTH_ENABLED}
      MPS_CORS_ORIGIN: http://${MPS_COMMON_NAME}:3001
      MPS_CORS_HEADERS: ${CORS_HEADERS}
      MPS_CORS_METHODS: ${CORS_METHODS}
      MPS_CONNECTION_STRING: ${MPS_CONNECTION_STRING}
      MPS_USE_DB: ${MPS_USE_DB}
    volumes:
      - private-volume:/mps-microservice/private
  rpsdb:
    image: postgres
    networks:
      - openamtnetwork
    restart: always
    environment:
      POSTGRES_DB: ${RPS_DB_NAME}
      POSTGRES_USER: ${RPS_DB_USER}
      POSTGRES_PASSWORD: ${RPS_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - ./data:/docker-entrypoint-initdb.d
  vault:
    image: "vault"
    networks:
      - openamtnetwork
    ports: 
      - "8200:8200"
    environment: 
      VAULT_DEV_ROOT_TOKEN_ID: ${RPS_VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add: 
      - IPC_LOCK
volumes:
    app-volume:
    private-volume:
networks: 
  openamtnetwork:
    driver: "bridge"
